services:
  sunshine:
    build: .
    image: retroshine:latest
    container_name: retro-shine
    restart: unless-stopped
    network_mode: host
    privileged: true
    entrypoint: ["/scripts/entrypoint.sh"]
    environment:
      - DISPLAY=:99
      - PULSE_SERVER=unix:/tmp/runtime-lizard/pulse/native
      - SDL_AUDIODRIVER=pulse
      - SUNSHINE_USER=admin
      - SUNSHINE_PASS=retro123
      - LIBVA_DRIVER_NAME=iHD
      - TZ=Europe/Stockholm
    volumes:
      - /dev/:/dev/:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./roms/:/roms/:ro
      - ./scraped-media/:/home/lizard/ES-DE/downloaded_media/:rw
      - sunshine-config:/home/lizard/.config/sunshine
    devices:
      - /dev/dri:/dev/dri:rw
      - /dev/uinput
      - /dev/uhid
    device_cgroup_rules:
      - 'c 13:* rmw'
      - 'c 226:* rmw'
      - 'c 10:223 rmw'

volumes:
  sunshine-config:
