sunshine_name = RetroCade
encoder = vaapi
capture = x11
adapter_name = /dev/dri/card1
output_name = 0

# display options removed in this Sunshine version
# display_name, display_fps, display_width, display_height are deprecated

hevc_mode = 2
av1_mode = 2
fec_percentage = 20
min_threads = 2
qp = 28

max_bitrate = 0

controller = enabled
gamepad = x360
keyboard = enabled
mouse = enabled
always_send_scancodes = enabled
